apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: forex-trading-bot-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
