apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: forex-redis-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: forex-redis
  labels:
    app: forex-redis
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: forex-redis
  template:
    metadata:
      labels:
        app: forex-redis
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          imagePullPolicy: Always
          command:
            - "redis-server"
            - "--appendonly"
            - "yes"
          ports:
            - name: redis
              containerPort: 6379
          volumeMounts:
            - name: redis-storage
              mountPath: /data
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
      volumes:
        - name: redis-storage
          persistentVolumeClaim:
            claimName: forex-redis-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: forex-redis
  labels:
    app: forex-redis
spec:
  type: ClusterIP
  selector:
    app: forex-redis
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
