apiVersion: v1
kind: Service
metadata:
  name: forex-trading-bot
  labels:
    app: forex-trading-bot
spec:
  type: NodePort
  selector:
    app: forex-trading-bot
  ports:
    - name: http
      port: 8000
      targetPort: 8000
